<a href="https://colab.research.google.com/github/Janhavi841/ABC/blob/main/Multi_lin_regre__sir_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from scipy.stats import chisquare
from scipy.stats import chi2_contingency
from scipy.stats import f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [5]:
df = pd.read_excel('/content/drive/MyDrive/SalesData_1.xlsx')

In [6]:
df.head()

   Advertising  Temperature  Gender Region   Sales
0        57.45        25.82  Female   West  433.23
1        47.93        38.39    Male  South  386.91
2        59.72        24.37    Male   West  518.70
3        72.85        18.73    Male   West  466.22
4        46.49        17.55  Female  North  345.77

In [7]:
import pandas as pd

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Advertising  700 non-null    float64
 1   Temperature  700 non-null    float64
 2   Gender       700 non-null    object
 3   Region       700 non-null    object
 4   Sales        700 non-null    float64
dtypes: float64(3), object(2)
memory usage: 27.5+ KB

In [9]:
# Convert categorical columns

In [12]:
# one hot encoding
df = pd.get_dummies(df,
                    columns=['Gender','Region'],
                    drop_first=True)

In [13]:
df.head()

,Advertising,Temperature,Sales,Gender_Male,Region_North,Region_South,Region_West
0,57.45,25.82,433.23,False,False,False,True
1,47.93,38.39,386.91,True,False,True,False
2,59.72,24.37,518.70,True,False,False,True
3,72.85,18.73,466.22,True,False,False,True
4,46.49,17.55,345.77,False,True,False,False

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Advertising   700 non-null    float64
 1   Temperature   700 non-null    float64
 2   Sales         700 non-null    float64
 3   Gender_Male   700 non-null    bool
 4   Region_North  700 non-null    bool
 5   Region_South  700 non-null    bool
 6   Region_West   700 non-null    bool
dtypes: bool(4), float64(3)
memory usage: 19.3 KB

In [15]:
# Define X and Y

X = df.drop('Sales',axis=1)
Y = df['Sales']

In [37]:
# train test split
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=20)

In [38]:
x_test

,Advertising,Temperature,Gender_Male,Region_North,Region_South,Region_West
535,50.71,43.11,1.0,0.0,0.0,1.0
281,59.93,33.40,0.0,1.0,0.0,0.0
324,34.91,43.82,1.0,0.0,1.0,0.0
645,45.91,18.12,0.0,1.0,0.0,0.0
10,43.05,31.69,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...
136,38.25,42.40,0.0,0.0,0.0,1.0
430,32.25,32.57,0.0,0.0,0.0,1.0
32,49.80,33.27,0.0,0.0,0.0,1.0
449,34.11,23.22,0.0,0.0,0.0,0.0
59,64.63,35.60,0.0,1.0,0.0,0.0

In [39]:
y_test

535    394.55
281    360.54
324    287.90
645    347.88
10     365.87
        ...
136    353.03
430    337.76
32     395.56
449    302.20
59     388.95
Name: Sales, Length: 140, dtype: float64

In [17]:
# create model
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [18]:
# prediction
y_pred = model.predict(x_test)

In [40]:
y_pred

array([284.32308249, 464.98780263, 240.14688965, 349.93259886,
       400.21492922, 467.0783287 , 510.0644812 , 324.58216989,
       331.74339601, 399.02266975, 340.24553637, 404.39032256,
       307.38545653, 386.70441938, 386.88148539, 402.87588291,
       392.22866992, 299.31745882, 363.76220554, 305.57779026,
       397.27699129, 409.37583234, 350.7151802 , 332.6802329 ,
       516.50463629, 282.56025965, 586.02127302, 458.61109015,
       510.7969978 , 247.13015219, 412.48729663, 291.22512602,
       335.07066613, 340.72811618, 312.38932699, 383.40293103,
       330.03059923, 412.75098108, 304.94040562, 325.25510928,
       359.74131372, 370.90206526, 253.4781479 , 277.60651625,
       527.7987006 , 382.57640523, 450.63998241, 419.66163169,
       365.5056068 , 423.53282216, 246.81134923, 354.19527555,
       293.76547897, 327.35908395, 304.48030426, 424.57743289,
       246.8572007 , 378.62566277, 456.52927215, 174.2744223 ,
       487.28815351, 306.76471841, 302.36396445, 339.11274142,
       329.16468814, 356.53502028, 467.21305013, 435.74341973,
       467.61457053, 374.94333744, 344.98783848, 444.69466895,
       313.23084932, 403.77082489, 495.47012207, 338.90168656,
       368.43972871, 489.09600078, 401.4694084 , 423.67795463,
       304.58677281, 291.19091521, 348.35612966, 258.61032172,
       391.64211838, 281.03321192, 325.36075437, 358.99449138,
       338.67124023, 337.46717457, 296.28949598, 310.02674804,
       270.29013045, 317.92914722, 413.85193828, 402.03610265,
       348.15739089, 375.39222772, 630.16339245, 388.5469541 ,
       369.56513478, 446.79015489, 496.65390092, 507.55417251,
       494.00741934, 418.37572283, 275.95491753, 439.91956579,
       416.45294057, 387.5354076 , 442.34909331, 383.74800683,
       481.26463175, 329.51427938, 458.64421269, 444.82702809,
       367.57024914, 412.78036787, 382.44701616, 427.71926033,
       297.13129841, 336.08239802, 396.01083404, 368.12695939,
       503.90476809, 432.61002829, 488.267953  , 269.50638478,
       289.91971873, 383.19633719, 392.03307845, 467.8786869 ,
       301.48747939, 414.70226597, 414.24913417, 330.17628048,
       338.3948231 , 238.81380699, 393.51913568, 226.39366502])

In [35]:
type(y_pred)

numpy.ndarray

In [41]:
y_test.head()

535    394.55
281    360.54
324    287.90
645    347.88
10     365.87
Name: Sales, dtype: float64

In [44]:
# summary
import statsmodels.api as sm

X1 = sm.add_constant(X)

model_sm = sm.OLS(Y,X1).fit()

print(model_sm.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.801
Model:                            OLS   Adj. R-squared:                  0.800
Method:                 Least Squares   F-statistic:                     466.2
Date:                Tue, 23 Jun 2026   Prob (F-statistic):          2.03e-239
Time:                        14:18:20   Log-Likelihood:                -3478.4
No. Observations:                 700   AIC:                             6971.
Df Residuals:                     693   BIC:                             7003.
Df Model:                           6
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const          126.5503      7.587     16.679      0.000     111.653     141.447
Advertising      4.6534      0.090     51.831      0.000       4.477       4.830
Temperature      0.2186      0.168      1.302      0.193      -0.111       0.548
Gender_Male     13.8267      2.666      5.186      0.000       8.592      19.062
Region_North   -18.8216      3.811     -4.938      0.000     -26.305     -11.339
Region_South    -5.1004      4.024     -1.268      0.205     -13.001       2.800
Region_West     22.5678      3.991      5.654      0.000      14.731      30.404
==============================================================================
Omnibus:                        0.581   Durbin-Watson:                   2.024
Prob(Omnibus):                  0.748   Jarque-Bera (JB):                0.435
Skew:                          -0.032   Prob(JB):                        0.805
Kurtosis:                       3.103   Cond. No.                         367.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Null Hypo: **Male** will not influnce sales.

p values is < 0.05

so null Hyp **REJECTED**

soo Temperature **WILL INFLUNCE** sales

- As we move from Female to male, Number of odd ratio will increase by 13.8

In [22]:
print(X.dtypes)

Advertising     float64
Temperature     float64
Gender_Male        bool
Region_North       bool
Region_South       bool
Region_West        bool
dtype: object

In [23]:
X = X.astype(float)

In [24]:
print(X.dtypes)

Advertising     float64
Temperature     float64
Gender_Male     float64
Region_North    float64
Region_South    float64
Region_West     float64
dtype: object